package es.udc.tfg.park_rest.model.enums;

public enum UserType {
  FAMILIAR_O_ACOMPAÑANTE, ORGANIZACIÓN_NO_GUBERNAMENTAL, PERSONA_CON_DISCAPACIDAD, PROFESIONAL_DEL_ÁMBITO_SOCIAL, EDUCATIVO_O_SANITARIO, TÉCNICO_A_O_PERSONAL_MUNICIPAL, VISITANTE_OCASIONAL
}
